Performed Code Refactoring
jxlsteam/jxls pull request #184
Opened 2022-03-25 21:24 UTC by vinaypatil03

Implemented the following 5 Code Refactoring's

1.  Rename Variable
2.  Extract Method
3. Push Down Method
4. Extract Class
5. Replaced Conditional with Polymorphism

2022-03-26 12:46 UTC, leonate commented on jxls/src/main/java/org/jxls/area/CommandData.java
> +    public Size getCommandSize() {
Renaming public methods is a breaking change, which means we will have to bump a major Jxls version and release Jxls 3.0.0. But releasing a new major version probably is not worth it unless we are ready also to  introduce new major features.

2022-03-26 18:24 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/util/CellRefUtil.java
> +                return isaBooleanT(rawSheetName);
I don't find isaBooleanT that understandable. The old code was easier to understand.

2022-03-26 18:58 UTC, SoltauFintel requested changes

2022-03-26 18:58 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/area/CommandData.java
> +//    public Size getSourceSize() {
I think it's always better to delete code instead of writing // before.

2022-03-26 18:58 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/util/CellRefUtil.java
> +    /**
In my opinion it should be a single line.

2022-03-26 18:58 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/util/CellRefUtil.java
> +        return new String[]{
I think there should be a blank.

2022-03-26 18:58 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/util/CellRefUtil.java
> +            return new String[]{reference};
....

2022-03-26 18:58 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/util/CellRefUtil.java
> +            return new String[]{partA, partB,};
.......

2022-03-26 18:58 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/area/XlsArea.java
> +            SourceSizeEvent sourceSizeEve = new SourceSizeEvent();
I don't understand this change. What's it for?

2022-03-26 18:58 UTC, SoltauFintel commented on jxls-site/src/site/markdown/reference/reader.md.vm
> +Let's use [data.xls](../xls/data.xls) Excel file with some  data to demonstrate this method
Error?! Why renaming departmentdata.xls to data.xls? departmentdata.xls exists, data.xls doesn't.

2022-03-26 18:58 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/transform/AbstractTransformer.java
> +//    public boolean isIgnoreColumnProps() {
better delete those lines

2022-03-26 18:58 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/util/LiteralsExtractor.java
> +    private String getString(String text, String cmd, Stack<Character> bracketsStack, Stack<Character> quotationsStack, int i, char symbol) {
Are these methods needed?

2022-03-26 18:58 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/util/SymbolManager.java
> +    public SymbolManager() {
public constructor and non-public methods?...

2022-03-26 19:05 UTC, SoltauFintel commented
**What is the goal of this PR?**

2022-06-08 08:22 UTC, SoltauFintel commented
Nothing else happened here. So unfortunately I have to reject this PR.

2022-06-08 08:22 UTC, closed without merging