#79 Multi-line and comment support
jxlsteam/jxls pull request #84
Opened 2021-01-12 14:16 UTC by alexlust

Multi-line and comment support question #79

https://github.com/jxlsteam/jxls/issues/79

2021-01-12 15:03 UTC, SoltauFintel commented
Please explain your change. e.g. screenshot of a multi-line SQL in Excel template

2021-01-12 15:49 UTC, alexlust commented
For testing i have created a small maven project
 
![image](https://user-images.githubusercontent.com/1311578/104337799-2686f980-54f6-11eb-96e2-f009f3931299.png)

![image](https://user-images.githubusercontent.com/1311578/104337761-1ec75500-54f6-11eb-9692-3358eb2bff0d.png)


E.g. if i have the following template:
 
if you have a new line in query "\n", you have a validation problem. 
If you try to escape this with "\\ n", you have an exception in JdbcHelper by run conn.prepareStatement (sql).
Right at the beginning we replace "\n" with our placeholder "__LINE_SEPARATOR__".
 So we don't get an exception with query validation. 
When the query runs in JdbcHelper, we replace the "__LINE_SEPARATOR__" by System.lineSeparator (). 
The original query is passed on unchanged from jxls-template to JdbcHelper and thus to stmt.executeQuery ().a

2021-01-12 15:59 UTC, alexlust commented
We have tested this solution in Report Server and with our master branch gemerged. We overwrited the files in your library with the modified files above.

2021-01-12 17:05 UTC, eduardo-rs commented
We also tested this with a simple Maven project using JXLS 2.9.0 (without ReportServer), so the code is independent of any ReportServer-specific code.

As we don't change the query anyhow, it is sent directly to the DB, which allows comments (single-line comments, multiline comments, etc) to be parsed correctly by the specific DB engine.

2021-01-12 17:28 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/builder/xls/XlsCommentAreaBuilder.java
> +				if (i != n)
please use { ... }

2021-01-12 17:35 UTC, SoltauFintel commented
We will contact you when we are finished with the code review.

2021-01-12 17:41 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/builder/xls/XlsCommentAreaBuilder.java
> +    private void extractLiterals(CellData cellData, String text, List<String> literalList) {
How do you think about creating a new class for this parsing?

And writing a testcase for it?

And method return value: List<String>
Is cellData needed?

2021-01-12 17:43 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/builder/xls/XlsCommentAreaBuilder.java
> +						logger.error(errorMessage);
I think there's no need to log an error if you also throw an exception. It might be the responsibility of the catcher to log the error.

2021-01-12 17:44 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/builder/xls/XlsCommentAreaBuilder.java
> +						throw new IllegalStateException(errorMessage);
IllegalStateException..?

2021-01-12 17:49 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/builder/xls/XlsCommentAreaBuilder.java
> +			if (literal.length() >= 3
maybe a constant or so for the "3" ..? COMMAND_PREFIX.length or COMMAND_PREFIX_LEN
After that you can remove the comment "// if the first 3 chars of literal are 'jx:'"

2021-01-12 17:50 UTC, SoltauFintel commented on jxls/src/main/java/org/jxls/builder/xls/XlsCommentAreaBuilder.java
> +					&& literal.substring(literal.length() - 3, literal.length()).equals(COMMAND_PREFIX)) {
Is this a literal.endsWith(COMMAND_PREFIX) ??

2021-01-12 17:56 UTC, SoltauFintel requested changes
Please make some fixes and then we start the 2nd code review round.

2021-01-15 16:12 UTC, SoltauFintel commented
Please use 4 spaces instead of 1 tab.

Please use this syntax:

if (...) {
// ...
} else { // curly braces in one line
// ...
}

see http://jxls.sourceforge.net/source_code.html

2021-02-15 16:20 UTC, eduardo-rs commented
Hi,
did you have a chance to look into this?
we tested this successfully in our application, so it would be nice if this feature gets integrated into jxls. We consider this being a very helpful feature as currently multilines and comments are not supported in the query element.

Regards,
Eduardo

2021-02-15 16:24 UTC, SoltauFintel commented
I've been waiting for you to report that you're done.

2021-02-15 16:27 UTC, eduardo-rs commented
Hi,
I thought you got automatically notified of this: 

alexander.lust
#79 Multi-line and comment support; revised syntax; tabs replaced by … …
27a19df

sorry for not notifying. 
Ok, we are done with the changes required.

Regards,
Eduardo

2021-02-15 16:31 UTC, SoltauFintel commented
Yes, I can see that. But I didn't get the impression that @alexlust had fixed all the spots. Maybe I'll make the corrections. I'll try that by Wednesday at the latest.

2021-02-15 16:36 UTC, eduardo-rs commented
I thought everything you mentioned was corrected, @alexlust can you pls also take a look ?

2021-02-17 15:38 UTC, SoltauFintel approved these changes

2021-02-17 15:39 UTC, merged

2021-02-17 16:16 UTC, SoltauFintel commented
### Code review

@alexlust  ( Cc @eduardo-rs  )

1) I don't understand:

            if (literal.length() >= COMMAND_PREFIX_LENGTH && literal.endsWith(XlsCommentAreaBuilder.COMMAND_PREFIX)) {
                // if the first 3 chars of literal are 'jx:'

first 3 chars and use of endsWith ??

And `literal.length() >= COMMAND_PREFIX_LENGTH &&`  is possibly not needed?!

2) Please write a **testcase** for LiteralsExtractor. I'm not sure if that class really works.

3) I made some changes! I have pushed them to branch **feature-79-fixes-2** to this github repository here. So you must update your forked repo (or delete it and fork again).


Would be nice if you can do it until Friday so we can release 2.10 _with_ this feature.

2021-02-18 18:55 UTC, alexlust commented
Hi, I adjusted, tested and checked the source code again. Now the changes based on the branch feature-79-fixes-2.

1. Yes, you can remove „literal.length() >= COMMAND_PREFIX_LENGTH &&“ You're right.
2. I wrote a JUnit-test for LiteralsExtractor

Best regards,

Alexanmder Lust

2021-02-18 22:44 UTC, alexlust commented
Excuse me. Am not so often in github. Is this the right branch?

2021-02-18 22:44 UTC, alexlust commented
https://github.com/jxlsteam/jxls/pull/100